<?php

use Illuminate\Database\Seeder;
///para crear usar php artisan make:seeder nombreTablaSeeder

//para ejecutar php artisan db:seed
use Illuminate\Support\Facades\DB;
class ParametricasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('parametricas')
        	->insert(array(
        		array(
        			'dominio'=>1,
        			'nombre'=>'documentos',
        			'id_padre'=>null,
        			'estado'=>null,
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Orden_Judicial',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Requerimiento_Fiscal',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Ficha_Internacion',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Informe_Social',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Informe_Psicologico',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Informe_Medico',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Informe_Pedagogico',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
        		array(
        			'dominio'=>1,
        			'nombre'=>'Otros_Documentos',
        			'id_padre'=>1,
        			'estado'=>'ingreso',
        		),
                array(
                    'dominio'=>1,
                    'nombre'=>'Coordinacion',
                    'id_padre'=>1,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Tratamiento_Medico',
                    'id_padre'=>7,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Receta_Medica',
                    'id_padre'=>7,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Memorandum_Egreso',
                    'id_padre'=>1,
                    'estado'=>'egreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Resolucion_Judicial',
                    'id_padre'=>1,
                    'estado'=>'egreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Informe_Medico_Egreso',
                    'id_padre'=>1,
                    'estado'=>'egreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Tratamiento_Medico_Egreso',
                    'id_padre'=>15,
                    'estado'=>'egreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Receta_Medica_Egreso',
                    'id_padre'=>15,
                    'estado'=>'egreso',
                ),
                array(
                    'dominio'=>1,
                    'nombre'=>'Certificado_Forence',
                    'id_padre'=>7,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>2,
                    'nombre'=>'problematica',
                    'id_padre'=>null,
                    'estado'=>null,
                ),
                array(
                    'dominio'=>2,
                    'nombre'=>'Violencia_Sexual_Comercial',
                    'id_padre'=>19,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>2,
                    'nombre'=>'Trata_ConFines_Explotacion_Sexual_Comercial',
                    'id_padre'=>19,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>2,
                    'nombre'=>'Trata_ConFines_Explotacion_Laboral',
                    'id_padre'=>19,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>2,
                    'nombre'=>'Violencia_Sexual',
                    'id_padre'=>19,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'ubicacion',
                    'id_padre'=>null,
                    'estado'=>null,
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Alojamiento',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Via_Publica',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Operativo',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Casa_Citas',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Domicilio_Particular',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Unidad_Educativa',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
                array(
                    'dominio'=>3,
                    'nombre'=>'Otro_Lugar',
                    'id_padre'=>24,
                    'estado'=>'ingreso',
                ),
        	));
    }
}
